name: CI/CD Pipeline for video storage Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    services:
      video-mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: auth_DB
        ports:
          - 3308:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -ppassword" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin' 

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Tests
      run: mvn test
      env:
        SPRING_DATASOURCE_URL: jdbc:mysql://video-mysql:3306/video_DB?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: admin

    - name: Build Docker Image for Video storage Service
      run: docker build -t video-storage-service:latest .

    - name: Run video storage Service Docker Container
      run: |
        docker network create video-network
        docker run --network video-network --name video_storage_service -e SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/vide_DB?useSSL=false -e SPRING_DATASOURCE_USERNAME=root -e SPRING_DATASOURCE_PASSWORD=admin -d -p 8084:8084 video-storage-service:latest

